"""Postmortem case-file generator — the chain of custody as a shareable markdown document.

`codeautopsy report <commit> <file> <line>` renders everything CodeAutopsy knows about one
crash — cause of death, blame, the AI's original decision and reasoning, attribution
confidence, and any lesson already learned for this class of bug — as one markdown file a
human can read, paste into a postmortem doc, or attach to an incident ticket. All the data
already exists (`fixbot.core.build_genealogy` + `fixbot.lessons.recall_lesson`); this module
is purely the rendering, so it's cheap to test in isolation from git/HTTP/the LLM.
"""

from __future__ import annotations

from codeautopsy.fixbot.models import Genealogy
from codeautopsy.provenance.models import LessonRecord


def render_postmortem(
    genealogy: Genealogy,
    *,
    lesson: LessonRecord | None = None,
    ci_run_url: str = "",
) -> str:
    """Render the full chain of custody as a markdown postmortem.

    Degrades gracefully at every step — an unresolved decision, a missing local incident log
    entry, or no recorded lesson are all legitimate, common states (not errors), so each
    section says so plainly instead of rendering blank or crashing.
    """
    resolved = bool(genealogy.decision_id)
    title = f"# Postmortem — `{genealogy.file_path}:{genealogy.line}`"

    header_lines = [f"**Commit:** `{genealogy.commit_sha[:12]}`"]
    if ci_run_url:
        header_lines.append(f"**Deployed by:** [CI run]({ci_run_url})")
    if genealogy.exc_type or genealogy.exc_message:
        header_lines.append(
            f"**Exception:** `{genealogy.exc_type}: {genealogy.exc_message}`"
        )
    header_lines.append(
        f"**Cause of death:** {genealogy.cause_of_death or '_no local incident log entry for this coordinate_'}"  # noqa: E501
    )

    if resolved:
        confidence_line = ""
        if genealogy.confidence is not None:
            factors = genealogy.confidence_factors or {}
            confidence_line = (
                f"\n**Attribution confidence:** {round(genealogy.confidence * 100)}% "
                f"({factors.get('label', '?')}, via {factors.get('match', '?')})"
            )
        reasoning_section = f"""## The AI's original reasoning

> {genealogy.reasoning_summary or "(no reasoning captured)"}

**Decision:** `{genealogy.decision_id}`
**Risk flags at write-time:** {", ".join(genealogy.risk_flags) or "none"}{confidence_line}
**Dev-time trace:** `{genealogy.decision_trace_id}`
**Dev-time span:** `{genealogy.decision_span_id}`"""
    elif genealogy.resolve_detail:
        # resolve_detail carries the provenance service's own reason the resolution came back
        # empty — e.g. "provenance service unreachable: ..." reads very differently from "no
        # matching provenance and no repo to blame," and a reader should be able to tell a
        # real outage apart from a legitimate no-match instead of seeing the same generic
        # message for both.
        reasoning_section = (
            "## The AI's original reasoning\n\n"
            f"_Could not resolve: {genealogy.resolve_detail}._"
        )
    else:
        reasoning_section = (
            "## The AI's original reasoning\n\n"
            "_No decision indexed for this line — it predates provenance capture, "
            "or wasn't AI-authored._"
        )

    custody_steps = [
        f"1. **Crash** — `{genealogy.exc_type or 'unknown exception'}` at "
        f"`{genealogy.file_path}:{genealogy.line}` (commit `{genealogy.commit_sha[:12]}`)",
        f"2. **Cause of death** — {genealogy.cause_of_death or 'unknown'}",
        "3. **Blame** — git-blame at the deployed commit resolves to the decision below",
    ]
    if resolved:
        custody_steps.append(
            f'4. **Decision** — `{genealogy.decision_id}`, reasoning: '
            f'"{genealogy.reasoning_summary}"'
        )
        custody_steps.append(
            f"5. **Risk flags at write-time** — {', '.join(genealogy.risk_flags) or 'none'}"
        )
    else:
        custody_steps.append("4. **Decision** — none found")
    if ci_run_url:
        custody_steps.append(f"{len(custody_steps) + 1}. **Deployed by** — [CI run]({ci_run_url})")

    if lesson is not None:
        lesson_section = f"""## Lesson learned

> {lesson.lesson}

Seen **{lesson.times_seen}x**. Last fix: {lesson.patch_summary or "(no patch summary recorded)"}"""
    else:
        lesson_section = (
            "## Lesson learned\n\n"
            "_No lesson recorded yet for this class of bug — run `codeautopsy fix` to learn one._"
        )

    return "\n\n".join(
        [
            title,
            "\n".join(header_lines),
            reasoning_section,
            "## Chain of custody\n\n" + "\n".join(custody_steps),
            lesson_section,
            "---\n_Generated by `codeautopsy report` — CodeAutopsy, git blame for the AI era._",
        ]
    )
